const productsData = [
    {
        id: 1,
        name: "Similac NeoSure Gold Infant Formula Powder",
        price: 63.00,
        image: "/images/similac_neosure_gold.jpg",
        description: "For 0-12 Months",
        releaseDate: "2023-10-01",
    },
    {
        id: 2,
        name: "Sebamed Baby Cleansing Bar 100g",
        price: 16.25,
        image: "/images/sebamed_baby_cleansing_bar.jpg",
        description: "Mild Cleansing for Baby",
        releaseDate: "2023-09-15",
    },
    {
        id: 3,
        name: "Sebamed Baby Gentle Wash With Allantoin 200ml",
        price: 26.75,
        image: "/images/sebamed_gentle_wash.jpg",
        description: "Gentle Wash for Sensitive Skin",
        releaseDate: "2023-08-20",
    },
    {
        id: 4,
        name: "Sebamed Baby Shampoo 500ml",
        price: 49.25,
        image: "/images/sebamed_shampoo.jpg",
        description: "Mild Shampoo for Baby",
        releaseDate: "2023-07-10",
    },
    {
        id: 5,
        name: "Sebamed Baby Wipes with Aloe Vera, Pack of 72's",
        price: 25.25,
        image: "/images/sebamed_baby_wipes.jpg",
        description: "Soft Wipes with Aloe Vera",
        releaseDate: "2023-06-05",
    },
    {
        id: 6,
        name: "Nestle Cerelac Apple Puree For 6+ Months Baby 90g",
        price: 6.50,
        image: "/images/cerelac_apple_puree.jpg",
        description: "Apple Puree for Baby",
        releaseDate: "2023-09-01",
    },
    {
        id: 7,
        name: "Nestle Cerelac Banana, Oat Puree For 6+ Months Baby 90g",
        price: 6.50,
        image: "/images/cerelac_banana_oat_puree.jpg",
        description: "Banana Oat Puree for Baby",
        releaseDate: "2023-08-25",
    },
    {
        id: 8,
        name: "Pigeon Baby Wipes, Pack of 80's",
        price: 22.00,
        image: "/images/pigeon_baby_wipes.jpg",
        description: "100% Pure Water Wipes",
        releaseDate: "2023-10-10",
    },
    {
        id: 9,
        name: "Huggies Extra Care Newborn Diapers, Pack of 21",
        price: 24.25,
        image: "/images/huggies_newborn_diapers.jpg",
        description: "For 4 - 6 kg Baby",
        releaseDate: "2023-09-12",
    },
    {
        id: 10,
        name: "Blemi Plus 2 HR Hydrolyzed Rice Protein Milk Formula For 6+ Months",
        price: 73.50,
        image: "/images/blemi_plus_formula.jpg",
        description: "Hydrolyzed Formula for Sensitive Tummies",
        releaseDate: "2023-08-30",
    },
    {
        id: 11,
        name: "Nestle Cerelac Infant Cereals With Iron + Wheat & Honey, Baby Formula 6+ Months 400g",
        price: 36.75,
        image: "/images/cerelac_infant_cereals.jpg",
        description: "Nutritious Cereal for Babies",
        releaseDate: "2023-08-05",
    },
    {
        id: 12,
        name: "Huggies Extra Care Cuddles, Size 4, Diaper Pants For 7-11 kg Baby",
        price: 76.25,
        image: "/images/huggies_extra_care_cuddles.jpg",
        description: "Comfortable Fit for Active Babies",
        releaseDate: "2023-07-15",
    },
    {
        id: 13,
        name: "Nido Forti Protectus 1+ Growing Up Milk Formula For 1-3 Year Baby 400g",
        price: 34.50,
        image: "/images/nido_forti_protectus.jpg",
        description: "Nutritional Support for Growing Kids",
        releaseDate: "2023-06-20",
    },
    {
        id: 14,
        name: "PediaSure Complete Chocolate With TripleSure System For 1-10 Year Kids 400g",
        price: 51.75,
        image: "/images/pediasure_complete.jpg",
        description: "Complete Nutrition for Kids",
        releaseDate: "2023-05-25",
    },
    {
        id: 15,
        name: "Nestle Cerelac Infant Cereals With Iron + Wheat & Fruits, Baby Formula 6+ Months 400g",
        price: 39.00,
        image: "/images/cerelac_infant_cereals_fruits.jpg",
        description: "Tasty & Nutritious Cereal",
        releaseDate: "2023-04-10",
    },
    {
        id: 16,
        name: "MAM Start Anti-Colic Baby Bottle 130ml",
        price: 49.00,
        image: "/images/mam_start_bottle.jpg",
        description: "Designed for Newborns",
        releaseDate: "2023-09-25",
    },
    {
        id: 17,
        name: "Chicco NaturalFeeling Baby Bottle 150ml",
        price: 55.00,
        image: "/images/chicco_bottle.jpg",
        description: "Ideal for Breastfed Babies",
        releaseDate: "2023-08-15",
    },
    {
        id: 18,
        name: "Tommee Tippee Closer to Nature Baby Bottle 260ml",
        price: 38.50,
        image: "/images/tommee_tippee_bottle.jpg",
        description: "Mimics Natural Breastfeeding",
        releaseDate: "2023-06-30",
    },
    {
        id: 19,
        name: "Philips Avent Anti-Colic Bottle 260ml",
        price: 65.00,
        image: "/images/philips_avent_bottle.jpg",
        description: "Reduces Colic Symptoms",
        releaseDate: "2023-07-20",
    },
    {
        id: 20,
        name: "Babyganics Baby Sunscreen SPF 50",
        price: 15.99,
        image: "/images/babyganics_sunscreen.jpg",
        description: "Gentle and Effective Sunscreen",
        releaseDate: "2023-06-01",
    },
    {
        id: 21,
        name: "Johnson's Baby Shampoo 500ml",
        price: 28.00,
        image: "/images/johnsons_shampoo.jpg",
        description: "No More Tears Formula",
        releaseDate: "2023-05-20",
    },
    {
        id: 22,
        name: "Aveeno Baby Daily Moisture Lotion 354ml",
        price: 29.99,
        image: "/images/aveeno_baby_lotion.jpg",
        description: "Clinically Proven to Moisturize for 24 Hours",
        releaseDate: "2023-04-15",
    },
    {
        id: 23,
        name: "Earth Mama Organic Nipple Butter 60ml",
        price: 18.50,
        image: "/images/earth_mama_nipple_butter.jpg",
        description: "Safe and Natural Nipple Cream",
        releaseDate: "2023-07-05",
    },
    {
        id: 24,
        name: "Burt's Bees Baby Bee Nourishing Lotion 200ml",
        price: 24.99,
        image: "/images/burts_bees_lotion.jpg",
        description: "Moisturizes and Soothes Baby's Skin",
        releaseDate: "2023-06-10",
    },
    {
        id: 25,
        name: "Huggies Dry Pants Diapers, Size 5, Pack of 16",
        price: 34.99,
        image: "/images/huggies_dry_pants.jpg",
        description: "Soft and Stretchy Fit",
        releaseDate: "2023-08-01",
    },
    {
        id: 26,
        name: "Baby Dove Rich Moisture Body Wash 400ml",
        price: 35.00,
        image: "/images/baby_dove_body_wash.jpg",
        description: "Hypoallergenic and pH-balanced",
        releaseDate: "2023-06-15",
    },
    {
        id: 27,
        name: "Pampers Premium Care Diapers, Size 3, Pack of 28",
        price: 42.00,
        image: "/images/pampers_premium_care.jpg",
        description: "Extra Soft and Gentle on Baby's Skin",
        releaseDate: "2023-05-30",
    },
    {
        id: 28,
        name: "Dr. Brown's Options+ Baby Bottle 270ml",
        price: 36.50,
        image: "/images/dr_browns_bottle.jpg",
        description: "Vent System Helps Reduce Colic",
        releaseDate: "2023-07-25",
    },
    {
        id: 29,
        name: "Nuk First Choice Baby Bottle 150ml",
        price: 23.50,
        image: "/images/nuk_first_choice_bottle.jpg",
        description: "Suitable for Breast and Bottle Feeding",
        releaseDate: "2023-08-15",
    },
    {
        id: 30,
        name: "Munchkin Latch Bottle 240ml",
        price: 19.99,
        image: "/images/munchkin_latch_bottle.jpg",
        description: "Breast-like Nipple Shape",
        releaseDate: "2023-06-28",
    },
    {
        id: 31,
        name: "Weleda Calendula Baby Cream 75ml",
        price: 18.00,
        image: "/images/weleda_baby_cream.jpg",
        description: "Nurturing Care for Delicate Skin",
        releaseDate: "2023-05-12",
    },
    {
        id: 32,
        name: "Carter's Baby Boy Bodysuits, Pack of 5",
        price: 29.99,
        image: "/images/carters_bodysuits.jpg",
        description: "Soft Cotton for Comfort",
        releaseDate: "2023-04-20",
    },
    {
        id: 33,
        name: "Gerber Organic Baby Food, Mixed Vegetables, 1 jar",
        price: 2.99,
        image: "/images/gerber_organic_food.jpg",
        description: "Organic and Nutritious",
        releaseDate: "2023-09-01",
    },
    {
        id: 34,
        name: "Huggies Little Snugglers Diapers, Size 1, Pack of 32",
        price: 39.00,
        image: "/images/huggies_little_snugglers.jpg",
        description: "Designed for Newborns",
        releaseDate: "2023-07-15",
    },
    {
        id: 35,
        name: "BabyBjorn Soft Bib, 2 Pack",
        price: 12.99,
        image: "/images/babybjorn_soft_bib.jpg",
        description: "Easy to Clean and Adjust",
        releaseDate: "2023-08-10",
    },
    {
        id: 36,
        name: "Chicco Baby Bottle Warmer",
        price: 49.99,
        image: "/images/chicco_bottle_warmer.jpg",
        description: "Heats Baby Food Quickly and Safely",
        releaseDate: "2023-06-01",
    },
    {
        id: 37,
        name: "Graco Pack 'n Play Playard",
        price: 129.99,
        image: "/images/graco_pack_n_play.jpg",
        description: "Portable and Versatile Playard",
        releaseDate: "2023-05-01",
    },
    {
        id: 38,
        name: "Medela Pump in Style Advanced Breast Pump",
        price: 249.00,
        image: "/images/medela_breast_pump.jpg",
        description: "Efficient Pumping for Nursing Mothers",
        releaseDate: "2023-03-25",
    },
    {
        id: 39,
        name: "Skip Hop Baby Play Gym",
        price: 79.99,
        image: "/images/skip_hop_play_gym.jpg",
        description: "Colorful and Engaging Activity Center",
        releaseDate: "2023-06-10",
    },
    {
        id: 40,
        name: "Evenflo Feeding Balance + Baby Bottle 250ml",
        price: 23.99,
        image: "/images/evenflo_feeding_bottle.jpg",
        description: "Supports Natural Feeding",
        releaseDate: "2023-04-15",
    },
    {
        id: 41,
        name: "Nuby Comfort 3-in-1 Electric Steam Sterilizer",
        price: 69.99,
        image: "/images/nuby_steam_sterilizer.jpg",
        description: "Keeps Baby's Bottles Clean and Safe",
        releaseDate: "2023-05-05",
    },
    {
        id: 42,
        name: "Boppy Original Nursing Pillow",
        price: 39.99,
        image: "/images/boppy_nursing_pillow.jpg",
        description: "Provides Comfort for Mom and Baby",
        releaseDate: "2023-06-20",
    },
    {
        id: 43,
        name: "Baby K'tan Original Baby Carrier",
        price: 59.99,
        image: "/images/baby_ktan_carrier.jpg",
        description: "Wraps Easily Without Tying",
        releaseDate: "2023-05-15",
    },
    {
        id: 44,
        name: "Pampers Pure Protection Diapers, Size 1, Pack of 32",
        price: 38.00,
        image: "/images/pampers_pure_protection.jpg",
        description: "Hypoallergenic and Soft",
        releaseDate: "2023-07-05",
    },
    {
        id: 45,
        name: "Snoo Smart Sleeper by Happiest Baby",
        price: 1295.00,
        image: "/images/snoo_smart_sleeper.jpg",
        description: "Automatic Rocking and White Noise",
        releaseDate: "2023-04-01",
    },
    {
        id: 46,
        name: "Munchkin Fresh Food Feeder",
        price: 9.99,
        image: "/images/munchkin_food_feeder.jpg",
        description: "For Fresh Fruit and Vegetables",
        releaseDate: "2023-08-01",
    },
    {
        id: 47,
        name: "Burt's Bees Baby Bee Skin Care Gift Set",
        price: 29.99,
        image: "/images/burts_bees_gift_set.jpg",
        description: "Gentle Care for Baby's Skin",
        releaseDate: "2023-06-05",
    },
    {
        id: 48,
        name: "Baby Trend Expedition Jogger Travel System",
        price: 229.99,
        image: "/images/baby_trend_jogger.jpg",
        description: "Convenient and Versatile Travel System",
        releaseDate: "2023-05-20",
    },
    {
        id: 49,
        name: "VTech Sit-to-Stand Learning Walker",
        price: 49.99,
        image: "/images/vtech_learning_walker.jpg",
        description: "Supports Baby's First Steps",
        releaseDate: "2023-06-15",
    },
    {
        id: 50,
        name: "Fisher-Price Rock with Me Zebra",
        price: 39.99,
        image: "/images/fisher_price_zebra.jpg",
        description: "Fun and Engaging Rocking Toy",
        releaseDate: "2023-07-30",
    },
];

export default productsData;
